import { writeBatch, collection, doc, serverTimestamp, getDocs } from 'firebase/firestore';
import { db } from './firebase';

const medicinesList = [
  // Previous medicines
  { name: 'D S P TAB', category: 'Tablets', stock: 20 },
  { name: 'NEWARROW-B12 FORTE', category: 'Tablets', stock: 5 },
  { name: 'NORFLOX-400 TAB', category: 'Tablets', stock: 4 },
  { name: 'NEUROBION FORTE TAB', category: 'Tablets', stock: 10 },
  { name: 'NEUROBION FORT TAB', category: 'Tablets', stock: 3 },
  { name: 'DOLOGESIC-SP TAB', category: 'Tablets', stock: 27 },
  { name: 'HEXAMENTIN-625 TAB', category: 'Tablets', stock: 4 },
  { name: 'AMOXYCLAV 625 TAB', category: 'Tablets', stock: 3 },
  { name: 'MONORIN-150 TAB', category: 'Tablets', stock: 25 },
  { name: 'MOKCAN CV 625', category: 'Tablets', stock: 2 },
  { name: 'FUNGICIP 200 TAB', category: 'Tablets', stock: 10 },
  { name: 'WICIP GOLD & FLU TAB', category: 'Tablets', stock: 20 },
  { name: 'NOVACLAV-625 TAB', category: 'Tablets', stock: 3 },
  { name: 'ORO-CV 625 TAB', category: 'Tablets', stock: 1 },
  { name: 'MUXANVUE CV 625', category: 'Tablets', stock: 1 },
  { name: 'KOLD TIME TAB', category: 'Tablets', stock: 10 },
  { name: 'DICLOGEM MR TAB', category: 'Tablets', stock: 20 },
  { name: 'FENAK PLUS TAB', category: 'Tablets', stock: 20 },
  { name: 'SEPTRAN DS TAB', category: 'Tablets', stock: 4 },
  { name: 'ONDEM MD 4 TAB', category: 'Tablets', stock: 5 },
  { name: 'BANDY PLUS TAB', category: 'Tablets', stock: 10 },
  { name: 'BRUFEN 400', category: 'Tablets', stock: 3 },
  { name: 'FLUKA-150 TAB', category: 'Tablets', stock: 3 },
  { name: 'NICIP COLD & FLU TAB', category: 'Tablets', stock: 30 },
  { name: 'VIGORE 100 TAB', category: 'Tablets', stock: 9 },
  { name: 'DEXALIFE TAB', category: 'Tablets', stock: 1 },
  { name: 'OFLOTAS-OZ TAB', category: 'Tablets', stock: 5 },
  { name: 'IBULAB TAB', category: 'Tablets', stock: 20 },
  { name: 'TRIMAZOLE-DS TAB', category: 'Tablets', stock: 9 },
  { name: 'ZEMURA-200 TAB', category: 'Tablets', stock: 10 },
  { name: 'CYPRODINE TAB 4MG', category: 'Tablets', stock: 1 },
  { name: 'DICLOGEM GREEN TAB', category: 'Tablets', stock: 40 },
  { name: 'DERIPHYLLIN TAB', category: 'Tablets', stock: 6 },
  { name: 'ASTHALIN 4 MG TAB', category: 'Tablets', stock: 6 },
  { name: 'DEXONA TAB', category: 'Tablets', stock: 30 },
  { name: 'ACILOC 300 MG TAB', category: 'Tablets', stock: 2 },
  { name: 'ENTERO QUINOL TAB', category: 'Tablets', stock: 3 },
  { name: 'METROGYL 400MG', category: 'Tablets', stock: 4 },
  { name: 'METROGYL 200MG TAB', category: 'Tablets', stock: 6 },
  { name: 'VERTIN 16 MG TAB', category: 'Tablets', stock: 2 },
  { name: 'DIGENE TAB MINT', category: 'Tablets', stock: 6 },
  { name: 'URASONE TAB', category: 'Tablets', stock: 1 },
  { name: 'DULCOFLEX TAB', category: 'Tablets', stock: 10 },
  { name: 'WYSOLONE 5MG TAB', category: 'Tablets', stock: 8 },
  { name: 'WYSOLONE 10MG TAB', category: 'Tablets', stock: 8 },
  { name: 'AMLOKIND 5 TAB', category: 'Tablets', stock: 6 },
  { name: 'NORFLUXACIN & TINIDAZOLE TAB', category: 'Tablets', stock: 4 },
  { name: 'ALMOX DT-250 TAB', category: 'Tablets', stock: 5 },
  { name: 'NICE TAMOL AP TAB', category: 'Tablets', stock: 8 },
  { name: 'NORILET-TZ TAB', category: 'Tablets', stock: 10 },
  { name: 'ETOFORD 120 TAB', category: 'Tablets', stock: 6 },
  { name: 'ULCERID TAB', category: 'Tablets', stock: 1 },
  { name: 'AZURI TAB 10TAB', category: 'Tablets', stock: 15 },
  { name: 'DOXYCHL LB CAP', category: 'Capsules', stock: 4 },
  { name: 'MAXIRICH CAP', category: 'Capsules', stock: 6 },
  { name: 'CANDIFORCE 200 CAP', category: 'Capsules', stock: 6 },
  { name: 'MANFORCE 100 CAP', category: 'Capsules', stock: 1 },
  { name: 'NUROKIND GOLD CAP', category: 'Capsules', stock: 5 },
  { name: 'MECOFOL PLUS NF CAP', category: 'Capsules', stock: 10 },
  { name: 'DECOSULES CAP', category: 'Capsules', stock: 6 },
  { name: 'KUFFDRYL-D CAP', category: 'Capsules', stock: 8 },
  { name: 'HEMO FORTE SYP 300ML', category: 'Syrups', stock: 3 },
  { name: 'AMPOXIN CV SUS 30ML', category: 'Syrups', stock: 10 },
  { name: 'C-ZEN PLUS SYP', category: 'Syrups', stock: 10 },
  { name: 'ALDIGESIC P+ SUS 60ML', category: 'Syrups', stock: 2 },
  { name: 'MONTULARG-LC SYP', category: 'Syrups', stock: 2 },
  { name: 'ACEFEN DS SUSPENSION', category: 'Syrups', stock: 3 },
  { name: 'ALKACITRUL SYP', category: 'Syrups', stock: 3 },
  { name: 'DEXORANGE SYRUP', category: 'Syrups', stock: 6 },
  { name: 'ALKASAL SYP', category: 'Syrups', stock: 2 },
  { name: 'HEPATOGLOBINE SYRUP 300ML', category: 'Syrups', stock: 2 },
  { name: 'MAGNAKUF-DX SYP', category: 'Syrups', stock: 4 },
  { name: 'TUSSCODINE-DX SYP', category: 'Syrups', stock: 5 },
  { name: 'TUSSOL BR SYP', category: 'Syrups', stock: 10 },
  { name: 'TUSSOL DRYL SYP', category: 'Syrups', stock: 10 },
  { name: 'FERCEE RED SYP', category: 'Syrups', stock: 2 },
  { name: 'OFLOX OZ SYP', category: 'Syrups', stock: 5 },
  { name: 'NICETAMUL MF SYP', category: 'Syrups', stock: 2 },
  { name: 'DRS MEDWIN', category: 'Syrups', stock: 8 },
  { name: 'MEDSETRON SYRUP', category: 'Syrups', stock: 5 },
  { name: 'DEF-M SUSPENSION', category: 'Syrups', stock: 5 },
  { name: 'SAFI 100ML', category: 'Syrups', stock: 1 },
  { name: 'SAFI 200ML', category: 'Syrups', stock: 2 },
  { name: 'CLUBETA GM GREEN 10GM', category: 'Creams/Gels/Sprays', stock: 6 },
  { name: 'DULUKIND STRONG GEL 30G', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'SUMO GEL 30GM', category: 'Creams/Gels/Sprays', stock: 4 },
  { name: 'LULITEC CREAM 30GM', category: 'Creams/Gels/Sprays', stock: 4 },
  { name: 'ACNESTAR GEL', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'BETNOVATE C OINT', category: 'Creams/Gels/Sprays', stock: 6 },
  { name: 'VOLINI GEL 12GM', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'DOLO PAIN RELIEF SPRAY', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'OMNIGEL SPRAY 55GM', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'OMNIGEL SPRAY 35GM', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'VOLINI SPRAY 15GM', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'MOOV 10GM', category: 'Creams/Gels/Sprays', stock: 4 },
  { name: 'MOOV SPRAY 15GM', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'MOOV SPRAY 35GM', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'OMNIGEL 20GM', category: 'Creams/Gels/Sprays', stock: 3 },
  { name: 'VICKS 5GM', category: 'Creams/Gels/Sprays', stock: 15 },
  { name: 'VICKS 12GM', category: 'Creams/Gels/Sprays', stock: 5 },
  { name: 'ZANDU BALM 8M', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'ZANDU BALM ULTRA 8M', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'TIGER BALM', category: 'Creams/Gels/Sprays', stock: 1 },
  { name: 'SANGAM OIL', category: 'Creams/Gels/Sprays', stock: 6 },
  { name: 'TIGER KING', category: 'Creams/Gels/Sprays', stock: 2 },
  { name: 'CLOP G CREAM', category: 'Creams/Gels/Sprays', stock: 4 },
  { name: 'ELECTROL POW ORANGE 4.4GM', category: 'Powders', stock: 50 },
  { name: 'K-MEDICO ORS POWDER', category: 'Powders', stock: 50 },
  { name: 'GASOFAST', category: 'Powders', stock: 20 },
  { name: 'G.C 100GM', category: 'Powders', stock: 4 },
  { name: 'G.C 200GM', category: 'Powders', stock: 2 },
  { name: 'ELECTRAL POWDER', category: 'Powders', stock: 31 },
  { name: 'ISABGOL 100GM', category: 'Powders', stock: 1 },
  { name: 'OXYTETRACYCLINE INJ 30ML', category: 'Injections', stock: 3 },
  { name: 'NUROKIND GOLD INJ', category: 'Injections', stock: 3 },
  { name: 'NEUROBION FORT AMP', category: 'Injections', stock: 2 },
  { name: 'CALVIT-12 INJ', category: 'Injections', stock: 2 },
  { name: 'TRINEUROSOL-H INJ', category: 'Injections', stock: 2 },
  { name: 'VITCOFOL VIAL', category: 'Injections', stock: 3 },
  { name: 'MAGENTA 20ML INJ', category: 'Injections', stock: 10 },
  { name: 'MERIDECA INJ 20ML', category: 'Injections', stock: 5 },
  { name: 'T.T BETT INJ', category: 'Injections', stock: 20 },
  { name: 'ALMOX 250 INJ', category: 'Injections', stock: 20 },
  { name: 'DEXASONE INJ 2ML', category: 'Injections', stock: 12 },
  { name: 'VICKS JAR', category: 'Others', stock: 1 },
  { name: 'UNWANTED KIT', category: 'Others', stock: 2 },
  { name: 'CUPID CHOCOLATE CONDOM', category: 'Others', stock: 10 },
  { name: 'CUPID SUPER DOTTED CONDOM', category: 'Others', stock: 5 },
  { name: 'PREGANIURTH CARD', category: 'Others', stock: 10 },

  // New medicines
  { name: 'Amokind-ST', category: 'Tablets', stock: 10 },
  { name: 'Neurobion Forte', category: 'Tablets', stock: 10 },
  { name: 'A to Z', category: 'Tablets', stock: 10 },
  { name: 'A to Z Gold', category: 'Tablets', stock: 10 },
  { name: 'Levocet', category: 'Tablets', stock: 10 },
  { name: 'Regestrone', category: 'Tablets', stock: 10 },
  { name: 'Telmikind AM', category: 'Tablets', stock: 10 },
  { name: 'Glimstar M2', category: 'Tablets', stock: 10 },
  { name: 'Zifi 200', category: 'Tablets', stock: 10 },
  { name: 'Taxim-O 200', category: 'Tablets', stock: 10 },
  { name: 'Mahagaba M75', category: 'Tablets', stock: 10 },
  { name: 'Manforce 100', category: 'Tablets', stock: 10 },
  { name: 'Zerodol SP', category: 'Tablets', stock: 10 },
  { name: 'Pan-D', category: 'Tablets', stock: 10 },
  { name: 'Clavam 625', category: 'Tablets', stock: 10 },
  { name: 'Combiflam', category: 'Tablets', stock: 10 },
  { name: 'Dolo 500', category: 'Tablets', stock: 10 },
  { name: 'Tegretal 200', category: 'Tablets', stock: 10 },
  { name: 'Zifi-100 DT', category: 'Tablets', stock: 10 },
  { name: 'Metrogyl 400', category: 'Tablets', stock: 10 },
  { name: 'Nurokind Plus', category: 'Tablets', stock: 10 },
  { name: 'Pregabalin', category: 'Tablets', stock: 10 },
  { name: 'Almox 500', category: 'Tablets', stock: 10 },
  { name: 'Fluzan 150', category: 'Tablets', stock: 10 },
  { name: 'Drotin-DS', category: 'Tablets', stock: 10 },
  { name: 'Dulcolax', category: 'Tablets', stock: 10 },
  { name: 'Asthalin Syrup', category: 'Syrups', stock: 10 },
  { name: 'Dolo 250 Syrup', category: 'Syrups', stock: 10 },
  { name: 'Livolin Syrup', category: 'Syrups', stock: 10 },
  { name: 'Electral Syrup', category: 'Syrups', stock: 10 },
  { name: 'Digene Gel Mint Syrup', category: 'Syrups', stock: 10 },
  { name: 'Asthakind Syrup', category: 'Syrups', stock: 10 },
  { name: 'TusQ-DX Syrup', category: 'Syrups', stock: 10 },
  { name: 'TusQ-Dryl Syrup', category: 'Syrups', stock: 10 },
  { name: 'TusQ Syrup', category: 'Syrups', stock: 10 },
  { name: 'Alkasol Syrup', category: 'Syrups', stock: 10 },
  { name: 'Amject 500 mg', category: 'Injections', stock: 10 },
  { name: 'Calvit-12 Injection', category: 'Injections', stock: 10 },
  { name: 'Trineurosol-H Injection', category: 'Injections', stock: 10 },
  { name: 'Clop-G Cream', category: 'Creams', stock: 10 },
  { name: 'Betnovate-GM Cream', category: 'Creams', stock: 10 },
  { name: 'Betnovate-N Cream', category: 'Creams', stock: 10 },
  { name: 'Derobin Cream', category: 'Creams', stock: 10 },
  { name: 'Clobeta-G Cream', category: 'Creams', stock: 10 },
  { name: 'Eldosone-N Cream', category: 'Creams', stock: 10 },
  { name: 'Nurament Cream', category: 'Creams', stock: 10 },
  { name: 'Ciplox Eye/Ear Drops', category: 'Drops', stock: 10 },
  { name: 'Moxi Eye Drops', category: 'Drops', stock: 10 },
  { name: 'Electral Orange Powder', category: 'Powders', stock: 10 },
  { name: 'Electral Powder Pouch', category: 'Powders', stock: 10 },
  { name: 'ORS Sachet', category: 'Powders', stock: 10 },
  { name: 'Clean & Clear Face Wash (50 ml)', category: 'Face Wash', stock: 10 },
  { name: 'Moov Gel', category: 'Gel', stock: 10 },
  { name: 'Digene Gel', category: 'Gel', stock: 10 },
  { name: 'Himalaya Baby Soap', category: 'Soap', stock: 10 },
  { name: 'Himalaya Shampoo (100 ml)', category: 'Shampoo', stock: 10 },
  { name: 'Hajmola Imli Jar', category: 'Other Products', stock: 10 },
  { name: 'Dabur Gripe Water', category: 'Other Products', stock: 10 },
  { name: 'Sankh Pushpi', category: 'Other Products', stock: 10 },
  { name: 'Vicks Action 500', category: 'Other Products', stock: 10 },
  { name: 'BhooSi (100 gm)', category: 'Other Products', stock: 10 },
  { name: 'G.D. 200 gm', category: 'Other Products', stock: 10 },
  { name: 'G.C. 200 gm', category: 'Other Products', stock: 10 },
  { name: 'G.C. 500 gm', category: 'Other Products', stock: 10 }
];

export async function seedMedicinesToFirestore() {
  const batch = writeBatch(db);
  const collectionRef = collection(db, 'medicines');
  
  // Get existing to avoid duplicating if run multiple times
  const existingDocs = await getDocs(collectionRef);
  const existingNames = new Set(existingDocs.docs.map(d => d.data().name?.toLowerCase()));

  let count = 0;
  // Firestore limit is 500 writes per batch. We have < 500 total, so it's safe.
  for (const med of medicinesList) {
    if (!existingNames.has(med.name.toLowerCase())) {
      const docRef = doc(collectionRef);
      batch.set(docRef, {
        name: med.name,
        category: med.category,
        manufacturer: '',
        price: 0,
        inStock: true,
        stock: med.stock || 10,
        description: '',
        image: '',
        createdAt: serverTimestamp()
      });
      count++;
    }
  }

  if (count > 0) {
    await batch.commit();
  }
  return count;
}

